<?
$metaboxes = array(
	'title'    => 'ألوان القالب',
	'en_title' => 'Theme Colors',
	'icon'     => '<i class="fa-solid fa-palette"></i>',
	'number'   => 5,
	'disc'     => 'تحكم كامل بألوان الموقع. اترك أي حقل فارغاً لاستخدام اللون الافتراضي من التصميم.',
	'fields'   => array(
		array(
			'type'  => 'Title',
			'title' => 'ألوان القالب العامة',
			'disc'  => 'تؤثر على الأزرار، الروابط، الهيدر، المقالات، والصفحات الداخلية.',
		),
		array(
			'title' => 'لون الموقع الأساسي',
			'type'  => 'Color',
			'id'    => 'site_color',
			'disc'  => 'متغير CSS: --uicolor (الأزرار، الروابط، تمييز الهيدر). الافتراضي من القالب: #1c61ef',
		),
		array(
			'title' => 'لون النص الأساسي',
			'type'  => 'Color',
			'id'    => 'text_Color',
			'disc'  => 'متغير CSS: --primary-text',
		),
		array(
			'title' => 'لون النص الثانوي',
			'type'  => 'Color',
			'id'    => 'kayan_secondary_text',
			'disc'  => 'متغير CSS: --secondarytext',
		),
		array(
			'title' => 'خلفية الفوتر',
			'type'  => 'Color',
			'id'    => 'kayan_footer_bg',
			'disc'  => 'فوتر القالب (.--YC-footer--). اتركه فارغاً للون الافتراضي.',
		),
		array(
			'type'  => 'Title',
			'title' => 'ألوان الهيدر',
			'disc'  => 'للرئيسية 2026: شفاف فوق الهيرو ثم يتحول عند التمرير.',
		),
		array(
			'title' => 'خلفية الهيدر عند التمرير',
			'type'  => 'Color',
			'id'    => 'kayan_header_scrolled_bg',
			'disc'  => 'الافتراضي: أبيض #ffffff',
		),
		array(
			'title' => 'لون نص الهيدر فوق الهيرو',
			'type'  => 'Color',
			'id'    => 'kayan_header_hero_text',
			'disc'  => 'الافتراضي: أبيض #ffffff',
		),
		array(
			'type'  => 'Title',
			'title' => 'ألوان الرئيسية 2026',
			'disc'  => 'تخص أقسام تصميم الرئيسية فقط. فارغ = ألوان index.html الافتراضية.',
		),
		array( 'title' => 'أزرق داكن (Navy)', 'type' => 'Color', 'id' => 'kayan_home_navy', 'disc' => '--navy — افتراضي #0A1F4E' ),
		array( 'title' => 'أزرق داكن 2', 'type' => 'Color', 'id' => 'kayan_home_navy2', 'disc' => '--navy2 — افتراضي #1A3A6B' ),
		array( 'title' => 'أزرق', 'type' => 'Color', 'id' => 'kayan_home_blue', 'disc' => '--blue — افتراضي #2980D4' ),
		array( 'title' => 'تركواز (تمييز)', 'type' => 'Color', 'id' => 'kayan_home_turq', 'disc' => '--turq — افتراضي #1AB8B8' ),
		array( 'title' => 'أكوا', 'type' => 'Color', 'id' => 'kayan_home_aqua', 'disc' => '--aqua — افتراضي #00D4D4' ),
		array( 'title' => 'ذهبي', 'type' => 'Color', 'id' => 'kayan_home_gold', 'disc' => '--gold — افتراضي #F4A428' ),
		array( 'title' => 'خلفية الصفحة', 'type' => 'Color', 'id' => 'kayan_home_bg', 'disc' => '--bg — افتراضي #F4F8FD' ),
		array( 'title' => 'لون النص', 'type' => 'Color', 'id' => 'kayan_home_text', 'disc' => '--text — افتراضي #1C2E44' ),
		array( 'title' => 'لون النص الثانوي', 'type' => 'Color', 'id' => 'kayan_home_text2', 'disc' => '--text2 — افتراضي #3A5068' ),
		array( 'title' => 'لون الحدود', 'type' => 'Color', 'id' => 'kayan_home_border', 'disc' => '--border — افتراضي #E2EAF5' ),
		array( 'title' => 'خلفية فوتر قسم 2026', 'type' => 'Color', 'id' => 'kayan_home_footer_bg', 'disc' => 'فوتر داخل أقسام الرئيسية — افتراضي نفس --navy' ),
		array( 'title' => 'لون النجاح', 'type' => 'Color', 'id' => 'kayan_home_success', 'disc' => '--success — افتراضي #18C96A' ),
		array( 'title' => 'لون واتساب', 'type' => 'Color', 'id' => 'kayan_home_wa', 'disc' => '--wa — افتراضي #25D366' ),
	),
);
